-- =========================================================
-- SOCCER CLUBS DATABASE SCHEMA & SEED (SOCCERWIKI)
-- =========================================================

CREATE TABLE IF NOT EXISTS public.soccer_clubs (
    id TEXT PRIMARY KEY,
    wiki_id INTEGER,
    name TEXT NOT NULL,
    short_name TEXT,
    league TEXT NOT NULL,
    city TEXT,
    country TEXT,
    badge TEXT,
    logo_url TEXT,
    prestige INTEGER DEFAULT 50,
    stadium TEXT,
    primary_color TEXT,
    secondary_color TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Row Level Security
ALTER TABLE public.soccer_clubs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read-only access to soccer_clubs" ON public.soccer_clubs FOR SELECT USING (true);

-- Upsert clubs
INSERT INTO public.soccer_clubs (id, wiki_id, name, short_name, league, city, country, badge, logo_url, prestige, stadium, primary_color, secondary_color)
VALUES
  ('club_2478', 2478, 'Brasil de Pelotas', 'GEB', 'REGIONAL', 'Pelotas (RS)', '🇧🇷', '🔴⚫', 'https://cdn.soccerwiki.org/images/logos/clubs/2478.png', 25, 'Bento Freitas', '#d90429', '#111111'),
  ('club_3436', 3436, 'São José-RS', 'SJO', 'REGIONAL', 'Porto Alegre (RS)', '🇧🇷', '🦅', 'https://cdn.soccerwiki.org/images/logos/clubs/3436.png', 18, 'Passo D''Areia', '#0a3871', '#ffffff'),
  ('club_3426', 3426, 'Ferroviária', 'AFE', 'REGIONAL', 'Araraquara (SP)', '🇧🇷', '🚂', 'https://cdn.soccerwiki.org/images/logos/clubs/3426.png', 22, 'Arena da Fonte', '#6b1d2f', '#ffffff'),
  ('club_3523', 3523, 'Maringá FC', 'MFC', 'REGIONAL', 'Maringá (PR)', '🇧🇷', '🐕', 'https://cdn.soccerwiki.org/images/logos/clubs/3523.png', 22, 'Willie Davids', '#005a36', '#ffffff'),
  ('club_2396', 2396, 'Campinense', 'CPC', 'REGIONAL', 'Campina Grande (PB)', '🇧🇷', '🦊', 'https://cdn.soccerwiki.org/images/logos/clubs/2396.png', 21, 'Amigão', '#c4122f', '#1a1a1a'),
  ('club_2815', 2815, 'Bangu', 'BAN', 'REGIONAL', 'Rio de Janeiro (RJ)', '🇧🇷', '🔴⚪', 'https://cdn.soccerwiki.org/images/logos/clubs/2815.png', 19, 'Moça Bonita', '#d90429', '#ffffff'),
  ('club_603', 603, 'Santa Cruz', 'SCZ', 'REGIONAL', 'Recife (PE)', '🇧🇷', '🐍', 'https://cdn.soccerwiki.org/images/logos/clubs/603.png', 32, 'Arruda', '#111111', '#d90429'),
  ('club_1232', 1232, 'Portuguesa', 'POR', 'REGIONAL', 'São Paulo (SP)', '🇧🇷', '🦁', 'https://cdn.soccerwiki.org/images/logos/clubs/1232.png', 30, 'Canindé', '#d90429', '#00543d'),
  ('club_2475', 2475, 'Volta Redonda', 'VRE', 'SERIE_C', 'Volta Redonda (RJ)', '🇧🇷', '⚡', 'https://cdn.soccerwiki.org/images/logos/clubs/2475.png', 36, 'Raulino de Oliveira', '#1a1a1a', '#ffd700'),
  ('club_4483', 4483, 'Brusque', 'BFC', 'SERIE_C', 'Brusque (SC)', '🇧🇷', '🟡', 'https://cdn.soccerwiki.org/images/logos/clubs/4483.png', 37, 'Augusto Bauer', '#ffd700', '#d90429'),
  ('club_3017', 3017, 'Botafogo-PB', 'BPB', 'SERIE_C', 'João Pessoa (PB)', '🇧🇷', '⭐', 'https://cdn.soccerwiki.org/images/logos/clubs/3017.png', 39, 'Almeidão', '#111111', '#ffffff'),
  ('club_3254', 3254, 'Operário-PR', 'VIC', 'SERIE_C', 'Ponta Grossa (PR)', '🇧🇷', '⚪⚫', 'https://cdn.soccerwiki.org/images/logos/clubs/3254.png', 38, 'Germano Krüger', '#111111', '#ffffff'),
  ('club_6455', 6455, 'Amazonas FC', 'EUR', 'SERIE_C', 'Manaus (AM)', '🇧🇷', '🐆', 'https://cdn.soccerwiki.org/images/logos/clubs/6455.png', 37, 'Arena da Amazônia', '#ffd700', '#111111'),
  ('club_301', 301, 'Paraná Clube', 'PAR', 'SERIE_C', 'Recife (PE)', '🇧🇷', '🇦🇹', 'https://cdn.soccerwiki.org/images/logos/clubs/301.png', 45, 'Aflitos', '#d90429', '#ffffff'),
  ('club_604', 604, 'Clube do Remo', 'BYE', 'SERIE_C', 'Belém (PA)', '🇧🇷', '🦁', 'https://cdn.soccerwiki.org/images/logos/clubs/604.png', 44, 'Baenão', '#002244', '#ffffff'),
  ('club_293', 293, 'Figueirense', 'FIG', 'SERIE_C', 'Florianópolis (SC)', '🇧🇷', '🌪️', 'https://cdn.soccerwiki.org/images/logos/clubs/293.png', 43, 'Orlando Scarpelli', '#111111', '#ffffff'),
  ('club_1478', 1478, 'Club Rubio Ñú', 'RUB', 'SERIE_C', 'Maceió (AL)', '🇧🇷', '🔵', 'https://cdn.soccerwiki.org/images/logos/clubs/1478.png', 42, 'Rei Pelé', '#003882', '#ffffff'),
  ('club_3073', 3073, 'Ypiranga de Erechim', 'SV', 'SERIE_C', 'Erechim (RS)', '🇧🇷', '🟡🟢', 'https://cdn.soccerwiki.org/images/logos/clubs/3073.jpg', 35, 'Colosso da Lagoa', '#ffd700', '#00543d'),
  ('club_923', 923, 'Sport Recife', 'SPO', 'SERIE_B', 'Recife (PE)', '🇧🇷', '🦁', 'https://cdn.soccerwiki.org/images/logos/clubs/923.png', 56, 'Ilha do Retiro', '#c4122f', '#1a1a1a'),
  ('club_1458', 1458, 'Ceará SC', 'CEA', 'SERIE_B', 'Fortaleza (CE)', '🇧🇷', '👴', 'https://cdn.soccerwiki.org/images/logos/clubs/1458.png', 55, 'Arena Castelão', '#1a1a1a', '#ffffff'),
  ('club_291', 291, 'Coritiba', 'CFC', 'SERIE_B', 'Curitiba (PR)', '🇧🇷', '🟢', 'https://cdn.soccerwiki.org/images/logos/clubs/291.png', 54, 'Couto Pereira', '#00543d', '#ffffff'),
  ('club_297', 297, 'Goiás', 'GOI', 'SERIE_B', 'Goiânia (GO)', '🇧🇷', '🦜', 'https://cdn.soccerwiki.org/images/logos/clubs/297.png', 53, 'Serrinha', '#00543d', '#ffffff'),
  ('club_303', 303, 'Ponte Preta', 'PP', 'SERIE_B', 'Campinas (SP)', '🇧🇷', '🐵', 'https://cdn.soccerwiki.org/images/logos/clubs/303.png', 50, 'Moisés Lucarelli', '#111111', '#ffffff'),
  ('club_1515', 1515, 'Guarani FC', 'GUA', 'SERIE_B', 'Campinas (SP)', '🇧🇷', '🏹', 'https://cdn.soccerwiki.org/images/logos/clubs/1515.png', 49, 'Brinco de Ouro', '#00543d', '#ffffff'),
  ('club_1414', 1414, 'Avaí FC', 'AFC', 'SERIE_B', 'Florianópolis (SC)', '🇧🇷', '🦁', 'https://cdn.soccerwiki.org/images/logos/clubs/1414.png', 51, 'Ressacada', '#0047ab', '#ffffff'),
  ('club_2379', 2379, 'Chapecoense', 'ACF', 'SERIE_B', 'Chapecó (SC)', '🇧🇷', '🏹', 'https://cdn.soccerwiki.org/images/logos/clubs/2379.png', 52, 'Arena Condá', '#00543d', '#ffffff'),
  ('club_3481', 3481, 'Novorizontino', 'GEN', 'SERIE_B', 'Novo Horizonte (SP)', '🇧🇷', '🐯', 'https://cdn.soccerwiki.org/images/logos/clubs/3481.png', 48, 'Jorjão', '#ffd700', '#111111'),
  ('club_302', 302, 'Paysandu', 'PAY', 'SERIE_B', 'Belém (PA)', '🇧🇷', '🐺', 'https://cdn.soccerwiki.org/images/logos/clubs/302.png', 52, 'Curuzu', '#0080ff', '#ffffff'),
  ('club_1457', 1457, 'Vila Nova', 'VN', 'SERIE_B', 'Goiânia (GO)', '🇧🇷', '🐅', 'https://cdn.soccerwiki.org/images/logos/clubs/1457.png', 49, 'OBA', '#d90429', '#ffffff'),
  ('club_294', 294, 'Flamengo', 'FLA', 'SERIE_A', 'Rio de Janeiro (RJ)', '🇧🇷', '🔴', 'https://cdn.soccerwiki.org/images/logos/clubs/294.png', 91, 'Maracanã', '#c4122f', '#111111'),
  ('club_300', 300, 'Palmeiras', 'PAL', 'SERIE_A', 'São Paulo (SP)', '🇧🇷', '🐷', 'https://cdn.soccerwiki.org/images/logos/clubs/300.png', 89, 'Allianz Parque', '#006437', '#ffffff'),
  ('club_306', 306, 'São Paulo FC', 'SAO', 'SERIE_A', 'São Paulo (SP)', '🇧🇷', '⚪', 'https://cdn.soccerwiki.org/images/logos/clubs/306.png', 87, 'MorumBIS', '#c4122f', '#ffffff'),
  ('club_290', 290, 'Corinthians', 'COR', 'SERIE_A', 'São Paulo (SP)', '🇧🇷', '🦅', 'https://cdn.soccerwiki.org/images/logos/clubs/290.png', 86, 'Neo Química Arena', '#111111', '#ffffff'),
  ('club_602', 602, 'Grêmio', 'GR&', 'SERIE_A', 'Porto Alegre (RS)', '🇧🇷', '🔵', 'https://cdn.soccerwiki.org/images/logos/clubs/602.png', 85, 'Arena do Grêmio', '#0080ff', '#111111'),
  ('club_298', 298, 'Internacional', 'INT', 'SERIE_A', 'Porto Alegre (RS)', '🇧🇷', '🇦🇹', 'https://cdn.soccerwiki.org/images/logos/clubs/298.png', 84, 'Beira-Rio', '#d4001a', '#ffffff'),
  ('club_286', 286, 'Atlético Mineiro', 'CAM', 'SERIE_A', 'Belo Horizonte (MG)', '🇧🇷', '🐔', 'https://cdn.soccerwiki.org/images/logos/clubs/286.png', 84, 'Arena MRV', '#111111', '#ffffff'),
  ('club_292', 292, 'Cruzeiro', 'CRZ', 'SERIE_A', 'Belo Horizonte (MG)', '🇧🇷', '🦊', 'https://cdn.soccerwiki.org/images/logos/clubs/292.png', 83, 'Mineirão', '#003882', '#ffffff'),
  ('club_288', 288, 'Botafogo', 'BOT', 'SERIE_A', 'Rio de Janeiro (RJ)', '🇧🇷', '⭐', 'https://cdn.soccerwiki.org/images/logos/clubs/288.png', 85, 'Nilton Santos', '#111111', '#ffffff'),
  ('club_295', 295, 'Fluminense', 'FLU', 'SERIE_A', 'Rio de Janeiro (RJ)', '🇧🇷', '🇭🇺', 'https://cdn.soccerwiki.org/images/logos/clubs/295.png', 84, 'Maracanã', '#8b1d2f', '#005a36'),
  ('club_307', 307, 'Vasco da Gama', 'VAS', 'SERIE_A', 'Rio de Janeiro (RJ)', '🇧🇷', '⛵', 'https://cdn.soccerwiki.org/images/logos/clubs/307.png', 83, 'São Januário', '#111111', '#ffffff'),
  ('club_304', 304, 'Santos FC', 'SFC', 'SERIE_A', 'Santos (SP)', '🇧🇷', '🐋', 'https://cdn.soccerwiki.org/images/logos/clubs/304.png', 83, 'Vila Belmiro', '#ffffff', '#111111'),
  ('club_1473', 1473, 'Bahia', 'BAH', 'SERIE_A', 'Salvador (BA)', '🇧🇷', '🔵🔴', 'https://cdn.soccerwiki.org/images/logos/clubs/1473.png', 81, 'Arena Fonte Nova', '#0047ab', '#d4001a'),
  ('club_296', 296, 'Fortaleza', 'FOR', 'SERIE_A', 'Fortaleza (CE)', '🇧🇷', '🦁', 'https://cdn.soccerwiki.org/images/logos/clubs/296.png', 81, 'Arena Castelão', '#003882', '#d4001a'),
  ('club_287', 287, 'Athletico Paranaense', 'CAP', 'SERIE_A', 'Curitiba (PR)', '🇧🇷', '🌪️', 'https://cdn.soccerwiki.org/images/logos/clubs/287.png', 82, 'Ligga Arena', '#c4122f', '#111111'),
  ('club_1447', 1447, 'RB Bragantino', 'RBB', 'SERIE_A', 'Bragança Paulista (SP)', '🇧🇷', '🐂', 'https://cdn.soccerwiki.org/images/logos/clubs/1447.png', 80, 'Nabi Abi Chedid', '#ffffff', '#c4122f'),
  ('club_270', 270, 'Boca Juniors', 'BOJ', 'ARGENTINA', 'Buenos Aires', '🇦🇷', '🔷🔶', 'https://cdn.soccerwiki.org/images/logos/clubs/270.png', 88, 'La Bombonera', '#002f6c', '#ffd700'),
  ('club_282', 282, 'River Plate', 'RIV', 'ARGENTINA', 'Buenos Aires', '🇦🇷', '⚪🔴', 'https://cdn.soccerwiki.org/images/logos/clubs/282.png', 89, 'Mâs Monumental', '#ffffff', '#d90429'),
  ('club_280', 280, 'Quilmes AC', 'QAC', 'ARGENTINA', 'Avellaneda', '🇦🇷', '🩵🤍', 'https://cdn.soccerwiki.org/images/logos/clubs/280.png', 82, 'El Cilindro', '#6ba4b8', '#ffffff'),
  ('club_275', 275, 'Independiente', 'IND', 'ARGENTINA', 'Avellaneda', '🇦🇷', '👹', 'https://cdn.soccerwiki.org/images/logos/clubs/275.png', 82, 'Libertadores de América', '#d90429', '#ffffff'),
  ('club_283', 283, 'Rosario Central', 'ROS', 'ARGENTINA', 'Buenos Aires', '🇦🇷', '🔵🔴', 'https://cdn.soccerwiki.org/images/logos/clubs/283.png', 80, 'Pedro Bidegain', '#002f6c', '#d90429'),
  ('club_273', 273, 'Gimnasia de Jujuy', 'GIM', 'ARGENTINA', 'La Plata', '🇦🇷', '🦁', 'https://cdn.soccerwiki.org/images/logos/clubs/273.png', 80, 'Jorge Luis Hirschi', '#d90429', '#ffffff'),
  ('club_281', 281, 'Racing Club', 'RAC', 'ARGENTINA', 'Rosario', '🇦🇷', '🟡🔵', 'https://cdn.soccerwiki.org/images/logos/clubs/281.png', 79, 'Gigante de Arroyito', '#002f6c', '#ffd700'),
  ('club_277', 277, 'Newell''s Old Boys', 'LAN', 'ARGENTINA', 'Rosario', '🇦🇷', '🔴⚫', 'https://cdn.soccerwiki.org/images/logos/clubs/277.png', 79, 'Marcelo Bielsa', '#d90429', '#111111'),
  ('club_284', 284, 'Talleres', 'SAN', 'ARGENTINA', 'Córdoba', '🇦🇷', '⚪🔵', 'https://cdn.soccerwiki.org/images/logos/clubs/284.png', 79, 'Mario Kempes', '#002f6c', '#ffffff'),
  ('club_439', 439, 'América-MEX', 'AME', 'LIGA_MX', 'Cidade do México', '🇲🇽', '🦅', 'https://cdn.soccerwiki.org/images/logos/clubs/439.png', 82, 'Estadio Azteca', '#ffd700', '#002f6c'),
  ('club_444', 444, 'Chivas Guadalajara', 'GDL', 'LIGA_MX', 'Guadalajara', '🇲🇽', '🐐', 'https://cdn.soccerwiki.org/images/logos/clubs/444.png', 81, 'Estadio Akron', '#d90429', '#ffffff'),
  ('club_443', 443, 'Cruz Azul', 'CAZ', 'LIGA_MX', 'Cidade do México', '🇲🇽', '🚂', 'https://cdn.soccerwiki.org/images/logos/clubs/443.png', 80, 'Estadio Ciudad de los Deportes', '#003882', '#ffffff'),
  ('club_452', 452, 'Mineros de Zacatecas', 'MIN', 'LIGA_MX', 'Monterrey', '🇲🇽', '🐯', 'https://cdn.soccerwiki.org/images/logos/clubs/452.png', 82, 'Estadio Universitario', '#ffd700', '#003882'),
  ('club_446', 446, 'CF Monterrey', 'MZN', 'LIGA_MX', 'Monterrey', '🇲🇽', '🤠', 'https://cdn.soccerwiki.org/images/logos/clubs/446.png', 81, 'Estadio BBVA', '#002f6c', '#ffffff'),
  ('club_451', 451, 'Toluca', 'TOL', 'LIGA_MX', 'Toluca', '🇲🇽', '👹', 'https://cdn.soccerwiki.org/images/logos/clubs/451.png', 79, 'Nemesio Díez', '#d90429', '#ffffff'),
  ('club_453', 453, 'Pumas UNAM', 'PUM', 'LIGA_MX', 'Cidade do México', '🇲🇽', '🐾', 'https://cdn.soccerwiki.org/images/logos/clubs/453.png', 80, 'Olímpico Universitario', '#00245d', '#c59b27'),
  ('club_447', 447, 'Pachuca', 'PAC', 'LIGA_MX', 'Pachuca', '🇲🇽', '🐹', 'https://cdn.soccerwiki.org/images/logos/clubs/447.png', 79, 'Estadio Hidalgo', '#002f6c', '#ffffff'),
  ('club_5228', 5228, 'Inter Miami', 'MIA', 'MLS', 'Miami', '🇺🇸', '🦩', 'https://cdn.soccerwiki.org/images/logos/clubs/5228.png', 78, 'Chase Stadium', '#f7b5cd', '#111111'),
  ('club_461', 461, 'LA Galaxy', 'GAL', 'MLS', 'Los Angeles', '🇺🇸', '⭐', 'https://cdn.soccerwiki.org/images/logos/clubs/461.png', 76, 'Dignity Health Sports Park', '#00245d', '#ffd700'),
  ('club_4260', 4260, 'LAFC', 'LAF', 'MLS', 'Los Angeles', '🇺🇸', '🦅', 'https://cdn.soccerwiki.org/images/logos/clubs/4260.png', 77, 'BMO Stadium', '#111111', '#c59b27'),
  ('club_1042', 1042, 'Caernarfon Town', 'CAE', 'MLS', 'Seattle', '🇺🇸', '🌲', 'https://cdn.soccerwiki.org/images/logos/clubs/1042.png', 75, 'Lumen Field', '#5d9732', '#005595'),
  ('club_3210', 3210, 'New York City', 'NYC', 'MLS', 'Nova York', '🇺🇸', '🗽', 'https://cdn.soccerwiki.org/images/logos/clubs/3210.png', 75, 'Yankee Stadium', '#6cace4', '#041e42'),
  ('club_3377', 3377, 'Lincoln Red Imps', 'LRI', 'MLS', 'Atlanta', '🇺🇸', '🔴⚫', 'https://cdn.soccerwiki.org/images/logos/clubs/3377.png', 74, 'Mercedes-Benz Stadium', '#80000a', '#111111'),
  ('club_625', 625, 'Al-Hilal', 'HIL', 'SAUDI_PRO', 'Riad', '🇸🇦', '🌙', 'https://cdn.soccerwiki.org/images/logos/clubs/625.png', 72, 'Kingdom Arena', '#002b80', '#ffffff'),
  ('club_665', 665, 'Al-Nassr', 'NSR', 'SAUDI_PRO', 'Riad', '🇸🇦', '👑', 'https://cdn.soccerwiki.org/images/logos/clubs/665.png', 72, 'Al-Awwal Park', '#ffd700', '#002b80'),
  ('club_627', 627, 'Al-Ittihad', 'ITH', 'SAUDI_PRO', 'Jidá', '🇸🇦', '🐅', 'https://cdn.soccerwiki.org/images/logos/clubs/627.png', 71, 'King Abdullah Sports City', '#ffd700', '#111111'),
  ('club_628', 628, 'Al-Ahli', 'AHL', 'SAUDI_PRO', 'Jidá', '🇸🇦', '🟢', 'https://cdn.soccerwiki.org/images/logos/clubs/628.png', 70, 'Prince Abdullah Al-Faisal', '#00543d', '#ffffff'),
  ('club_626', 626, 'Al-Shabab', 'SHA', 'SAUDI_PRO', 'Riad', '🇸🇦', '⚪⚫', 'https://cdn.soccerwiki.org/images/logos/clubs/626.png', 68, 'Al Shabab Stadium', '#ffffff', '#111111'),
  ('club_666', 666, 'Al-Ettifaq', 'ITF', 'SAUDI_PRO', 'Dammam', '🇸🇦', '🟢🔴', 'https://cdn.soccerwiki.org/images/logos/clubs/666.png', 67, 'Prince Mohamed bin Fahd', '#00543d', '#d90429'),
  ('club_47', 47, 'Manchester City', 'MCI', 'PREMIER_LEAGUE', 'Manchester', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', '⛵', 'https://cdn.soccerwiki.org/images/logos/clubs/47.png', 98, 'Etihad Stadium', '#6cabdd', '#1c2c5b'),
  ('club_1', 1, 'Arsenal', 'ARS', 'PREMIER_LEAGUE', 'Londres', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', '🔴⚪', 'https://cdn.soccerwiki.org/images/logos/clubs/1.png', 95, 'Emirates Stadium', '#db0007', '#ffffff'),
  ('club_44', 44, 'Liverpool', 'LIV', 'PREMIER_LEAGUE', 'Liverpool', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', '🦅', 'https://cdn.soccerwiki.org/images/logos/clubs/44.png', 96, 'Anfield', '#c8102e', '#00b2a9'),
  ('club_2', 2, 'Aston Villa', 'AVL', 'PREMIER_LEAGUE', 'Birmingham', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', '🦁', 'https://cdn.soccerwiki.org/images/logos/clubs/2.png', 89, 'Villa Park', '#670e36', '#95bfe5'),
  ('club_56', 56, 'Tottenham', 'NCO', 'PREMIER_LEAGUE', 'Londres', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', '🐓', 'https://cdn.soccerwiki.org/images/logos/clubs/56.png', 90, 'Tottenham Hotspur Stadium', '#ffffff', '#132257'),
  ('club_38', 38, 'Ipswich Town', 'IPS', 'PREMIER_LEAGUE', 'Londres', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', '🦁', 'https://cdn.soccerwiki.org/images/logos/clubs/38.png', 92, 'Stamford Bridge', '#034694', '#ffffff'),
  ('club_48', 48, 'Newcastle', 'MAN', 'PREMIER_LEAGUE', 'Newcastle', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', '🏰', 'https://cdn.soccerwiki.org/images/logos/clubs/48.png', 89, 'St. James'' Park', '#111111', '#ffffff'),
  ('club_46', 46, 'Macclesfield FC', 'MAC', 'PREMIER_LEAGUE', 'Manchester', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', '👹', 'https://cdn.soccerwiki.org/images/logos/clubs/46.png', 93, 'Old Trafford', '#da291c', '#111111'),
  ('club_163', 163, 'Real Madrid', 'RMA', 'LA_LIGA', 'Madri', '🇪🇸', '👑', 'https://cdn.soccerwiki.org/images/logos/clubs/163.png', 99, 'Santiago Bernabéu', '#ffffff', '#4d1e8c'),
  ('club_140', 140, 'FC Barcelona', 'BAR', 'LA_LIGA', 'Barcelona', '🇪🇸', '🔴🔵', 'https://cdn.soccerwiki.org/images/logos/clubs/140.png', 97, 'Spotify Camp Nou', '#004d98', '#a50044'),
  ('club_139', 139, 'Atlético Madrid', 'ATM', 'LA_LIGA', 'Madri', '🇪🇸', '🐻', 'https://cdn.soccerwiki.org/images/logos/clubs/139.png', 92, 'Cívitas Metropolitano', '#cb3524', '#ffffff'),
  ('club_138', 138, 'Athletic Club', 'ATH', 'LA_LIGA', 'Bilbao', '🇪🇸', '🦁', 'https://cdn.soccerwiki.org/images/logos/clubs/138.png', 88, 'San Mamés', '#ee2524', '#ffffff'),
  ('club_164', 164, 'Real Murcia', 'RMU', 'LA_LIGA', 'San Sebastián', '🇪🇸', '⚪🔵', 'https://cdn.soccerwiki.org/images/logos/clubs/164.png', 87, 'Reale Arena', '#0067b1', '#ffffff'),
  ('club_162', 162, 'Real Betis', 'BET', 'LA_LIGA', 'Sevilha', '🇪🇸', '🟢⚪', 'https://cdn.soccerwiki.org/images/logos/clubs/162.png', 86, 'Benito Villamarín', '#0bb364', '#ffffff'),
  ('club_166', 166, 'Sevilla', 'RCR', 'LA_LIGA', 'Sevilha', '🇪🇸', '⚔️', 'https://cdn.soccerwiki.org/images/logos/clubs/166.png', 86, 'Ramón Sánchez-Pizjuán', '#d4001a', '#ffffff'),
  ('club_109', 109, 'Internazionale', 'INT', 'SERIE_A_ITALIA', 'Milão', '🇮🇹', '🐍', 'https://cdn.soccerwiki.org/images/logos/clubs/109.png', 95, 'San Siro', '#001489', '#000000'),
  ('club_115', 115, 'AC Milan', 'MIL', 'SERIE_A_ITALIA', 'Milão', '🇮🇹', '🔴⚫', 'https://cdn.soccerwiki.org/images/logos/clubs/115.png', 93, 'San Siro', '#fb090b', '#000000'),
  ('club_110', 110, 'Juventus', 'JUV', 'SERIE_A_ITALIA', 'Turim', '🇮🇹', '⚪⚫', 'https://cdn.soccerwiki.org/images/logos/clubs/110.png', 93, 'Allianz Stadium', '#000000', '#ffffff'),
  ('club_116', 116, 'Modena', 'MOD', 'SERIE_A_ITALIA', 'Nápoles', '🇮🇹', '🌋', 'https://cdn.soccerwiki.org/images/logos/clubs/116.png', 90, 'Diego Armando Maradona', '#003882', '#ffffff'),
  ('club_122', 122, 'AS Roma', 'REG', 'SERIE_A_ITALIA', 'Roma', '🇮🇹', '🐺', 'https://cdn.soccerwiki.org/images/logos/clubs/122.png', 89, 'Stadio Olimpico', '#8e1f2f', '#f0bc42'),
  ('club_111', 111, 'SS Lazio', 'LAZ', 'SERIE_A_ITALIA', 'Roma', '🇮🇹', '🦅', 'https://cdn.soccerwiki.org/images/logos/clubs/111.png', 88, 'Stadio Olimpico', '#87d8f7', '#ffffff'),
  ('club_101', 101, 'Catania FC', 'CAT', 'SERIE_A_ITALIA', 'Bérgamo', '🇮🇹', '女神', 'https://cdn.soccerwiki.org/images/logos/clubs/101.png', 89, 'Gewiss Stadium', '#1e71b8', '#000000'),
  ('club_391', 391, 'Bayern München', 'FCB', 'BUNDESLIGA', 'Munique', '🇩🇪', '🦁', 'https://cdn.soccerwiki.org/images/logos/clubs/391.png', 97, 'Allianz Arena', '#dc052d', '#0066b2'),
  ('club_395', 395, 'Eintracht Frankfurt', 'SGE', 'BUNDESLIGA', 'Dortmund', '🇩🇪', '🐝', 'https://cdn.soccerwiki.org/images/logos/clubs/395.png', 93, 'Signal Iduna Park', '#fde100', '#000000'),
  ('club_389', 389, 'Arminia Bielefeld', 'ARM', 'BUNDESLIGA', 'Leverkusen', '🇩🇪', '💊', 'https://cdn.soccerwiki.org/images/logos/clubs/389.png', 94, 'BayArena', '#e32221', '#000000'),
  ('club_2200', 2200, 'Sunshine Stars', 'SUN', 'BUNDESLIGA', 'Leipzig', '🇩🇪', '🐂', 'https://cdn.soccerwiki.org/images/logos/clubs/2200.png', 91, 'Red Bull Arena', '#ffffff', '#d81e05'),
  ('club_397', 397, 'Erzgebirge Aue', 'ERZ', 'BUNDESLIGA', 'Frankfurt', '🇩🇪', '🦅', 'https://cdn.soccerwiki.org/images/logos/clubs/397.png', 88, 'Deutsche Bank Park', '#e1000f', '#000000'),
  ('club_418', 418, 'VfL Bochum', 'BOC', 'BUNDESLIGA', 'Stuttgart', '🇩🇪', '🐊', 'https://cdn.soccerwiki.org/images/logos/clubs/418.png', 87, 'MHPArena', '#ffffff', '#e30613'),
  ('club_1079', 1079, 'Vissel Kobe', 'VIS', 'J_LEAGUE', 'Kobe', '🇯🇵', '⚓', 'https://cdn.soccerwiki.org/images/logos/clubs/1079.png', 73, 'Noevir Stadium Kobe', '#9e0039', '#ffffff'),
  ('club_506', 506, 'Yokohama F. Marinos', 'YFM', 'J_LEAGUE', 'Yokohama', '🇯🇵', '⛵', 'https://cdn.soccerwiki.org/images/logos/clubs/506.png', 73, 'Nissan Stadium', '#003882', '#d90429'),
  ('club_527', 527, 'Kawasaki Frontale', 'KWF', 'J_LEAGUE', 'Kawasaki', '🇯🇵', '🐬', 'https://cdn.soccerwiki.org/images/logos/clubs/527.png', 72, 'Todoroki Athletics Stadium', '#58b2dc', '#111111'),
  ('club_505', 505, 'FK Mariupol', 'MAR', 'J_LEAGUE', 'Saitama', '🇯🇵', '💎', 'https://cdn.soccerwiki.org/images/logos/clubs/505.png', 73, 'Saitama Stadium 2002', '#d90429', '#111111'),
  ('club_497', 497, 'OFI Crete', 'OFI', 'J_LEAGUE', 'Kashima', '🇯🇵', '🦌', 'https://cdn.soccerwiki.org/images/logos/clubs/497.png', 72, 'Kashima Soccer Stadium', '#9e1b32', '#111111'),
  ('club_500', 500, 'Nagoya Grampus', 'NAG', 'J_LEAGUE', 'Nagoya', '🇯🇵', '🐋', 'https://cdn.soccerwiki.org/images/logos/clubs/500.png', 71, 'Toyota Stadium', '#e4002b', '#ffd700'),
  ('club_265', 265, 'Zenit', 'ZEN', 'RUSSIA', 'São Petersburgo', '🇷🇺', '🦁', 'https://cdn.soccerwiki.org/images/logos/clubs/265.png', 82, 'Gazprom Arena', '#00bfff', '#ffffff'),
  ('club_263', 263, 'Spartak Moskva', 'SPM', 'RUSSIA', 'Moscou', '🇷🇺', '🔴⚪', 'https://cdn.soccerwiki.org/images/logos/clubs/263.png', 80, 'Lukoil Arena', '#d90429', '#ffffff'),
  ('club_254', 254, 'CSKA Moskva', 'CSK', 'RUSSIA', 'Moscou', '🇷🇺', '🐴', 'https://cdn.soccerwiki.org/images/logos/clubs/254.png', 80, 'VEB Arena', '#003882', '#d90429'),
  ('club_258', 258, 'Lokomotiv Moskva', 'LOK', 'RUSSIA', 'Moscou', '🇷🇺', '🚂', 'https://cdn.soccerwiki.org/images/logos/clubs/258.png', 79, 'RZD Arena', '#00543d', '#d90429'),
  ('club_2217', 2217, 'Krasnodar', 'APS', 'RUSSIA', 'Krasnodar', '🇷🇺', '🐂', 'https://cdn.soccerwiki.org/images/logos/clubs/2217.png', 79, 'Krasnodar Stadium', '#00543d', '#111111'),
  ('club_348', 348, 'Shakhtar Donetsk', 'SHA', 'GLOBAL_AVULSOS', 'Donetsk', '🇺🇦', '⚒️', 'https://cdn.soccerwiki.org/images/logos/clubs/348.png', 84, 'Arena Lviv', '#f47920', '#111111'),
  ('club_347', 347, 'Dynamo Kyiv', 'DYN', 'GLOBAL_AVULSOS', 'Kiev', '🇺🇦', '🔷', 'https://cdn.soccerwiki.org/images/logos/clubs/347.png', 82, 'Olimpiyskiy', '#003882', '#ffffff'),
  ('club_373', 373, 'Olympiacos', 'OLY', 'GLOBAL_AVULSOS', 'Pireu', '🇬🇷', '🔴⚪', 'https://cdn.soccerwiki.org/images/logos/clubs/373.png', 82, 'Karaiskakis Stadium', '#d90429', '#ffffff'),
  ('club_374', 374, 'Panathinaikos', 'PAO', 'GLOBAL_AVULSOS', 'Atenas', '🇬🇷', '☘️', 'https://cdn.soccerwiki.org/images/logos/clubs/374.png', 81, 'Apostolos Nikolaidis', '#00543d', '#ffffff'),
  ('club_372', 372, 'AEK Athens', 'AEK', 'GLOBAL_AVULSOS', 'Atenas', '🇬🇷', '🦅', 'https://cdn.soccerwiki.org/images/logos/clubs/372.png', 80, 'OPAP Arena', '#ffd700', '#111111'),
  ('club_755', 755, 'Aldershot Town', 'ALD', 'GLOBAL_AVULSOS', 'Salônica', '🇬🇷', '🦅', 'https://cdn.soccerwiki.org/images/logos/clubs/755.png', 80, 'Toumba Stadium', '#111111', '#ffffff'),
  ('club_1251', 1251, 'Al Ahly (Egito)', 'AHL', 'GLOBAL_AVULSOS', 'Cairo', '🇪🇬', '🦅', 'https://cdn.soccerwiki.org/images/logos/clubs/1251.jpg', 82, 'Cairo International', '#d90429', '#ffffff'),
  ('club_1252', 1252, 'Zamalek (Egito)', 'SAD', 'GLOBAL_AVULSOS', 'Giza', '🇪🇬', '🏹', 'https://cdn.soccerwiki.org/images/logos/clubs/1252.png', 80, 'Cairo International', '#ffffff', '#d90429'),
  ('club_512', 512, 'Ulsan HD', 'SAM', 'GLOBAL_AVULSOS', 'Ulsan', '🇰🇷', '🐯', 'https://cdn.soccerwiki.org/images/logos/clubs/512.png', 74, 'Ulsan Munsu', '#003882', '#ffd700'),
  ('club_515', 515, 'Jeonbuk Hyundai', 'APO', 'GLOBAL_AVULSOS', 'Jeonju', '🇰🇷', 'Motors', 'https://cdn.soccerwiki.org/images/logos/clubs/515.png', 74, 'Jeonju World Cup', '#00543d', '#ffffff'),
  ('club_516', 516, 'Gamba Osaka', 'GAM', 'GLOBAL_AVULSOS', 'Seul', '🇰🇷', '🔴⚫', 'https://cdn.soccerwiki.org/images/logos/clubs/516.png', 73, 'Seoul World Cup', '#111111', '#d90429'),
  ('club_2470', 2470, 'AS Melfi', 'MEL', 'GLOBAL_AVULSOS', 'Xangai', '🇨🇳', '🐉', 'https://cdn.soccerwiki.org/images/logos/clubs/2470.png', 72, 'Pudong Football Stadium', '#d90429', '#ffd700'),
  ('club_509', 509, 'Sporting Cristal', 'SCL', 'GLOBAL_AVULSOS', 'Jinan', '🇨🇳', '🟠', 'https://cdn.soccerwiki.org/images/logos/clubs/509.png', 71, 'Jinan Olympic Sports Center', '#f47920', '#ffffff'),
  ('club_507', 507, 'Egaleo', 'EGA', 'GLOBAL_AVULSOS', 'Pequim', '🇨🇳', '🟢', 'https://cdn.soccerwiki.org/images/logos/clubs/507.png', 71, 'Workers Stadium', '#00543d', '#ffd700')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  league = EXCLUDED.league,
  logo_url = EXCLUDED.logo_url,
  prestige = EXCLUDED.prestige;
