/* ==========================================================================
   CLUBS & LEAGUES DATABASE
   Realistic football ecosystem from grassroots to global giants
   ========================================================================== */

export const LEAGUES = {
  REGIONAL: {
    id: 'regional',
    name: 'Série D / Acesso Regional',
    country: '🇧🇷',
    repTier: 1,
    avgSalaryRange: [2500, 8000],
    signingBonusRange: [0, 20000],
  },
  SERIE_B: {
    id: 'serie_b',
    name: 'Brasileirão Série B',
    country: '🇧🇷',
    repTier: 2,
    avgSalaryRange: [15000, 45000],
    signingBonusRange: [50000, 250000],
  },
  SERIE_A: {
    id: 'serie_a',
    name: 'Brasileirão Série A (Elite)',
    country: '🇧🇷',
    repTier: 3,
    avgSalaryRange: [80000, 450000],
    signingBonusRange: [500000, 3000000],
  },
  MONEY_LEAGUE: {
    id: 'money_league',
    name: 'Liga das Arábias / China (Petrodólares)',
    country: '🇸🇦',
    repTier: 2, // Low international prestige, massive financial power
    avgSalaryRange: [600000, 2500000],
    signingBonusRange: [5000000, 20000000],
  },
  EUROPA_MEDIA: {
    id: 'europa_media',
    name: 'Europa Vitrine (Portugal/Espanha/Holanda)',
    country: '🇪🇺',
    repTier: 4,
    avgSalaryRange: [120000, 500000],
    signingBonusRange: [1000000, 4000000],
  },
  GIGANTES_EUROPA: {
    id: 'gigantes_europa',
    name: 'Gigantes da Europa (Champions League)',
    country: '🌍',
    repTier: 5,
    avgSalaryRange: [1500000, 5000000],
    signingBonusRange: [15000000, 60000000],
  },
};

export const CLUBS = [
  // --- Série D / Regionais (Clubes Formadores) ---
  {
    id: 'sao-jose-rs',
    name: 'São José-RS',
    league: 'REGIONAL',
    city: 'Porto Alegre (RS)',
    country: '🇧🇷',
    badge: '🦅',
    colors: { primary: '#0a3871', secondary: '#ffffff', text: '#ffffff' },
    prestige: 15,
    stadium: 'Passo D\'Areia',
    rival: 'Caxias',
  },
  {
    id: 'pelotas',
    name: 'Pelotas',
    league: 'REGIONAL',
    city: 'Pelotas (RS)',
    country: '🇧🇷',
    badge: '🐺',
    colors: { primary: '#0047ab', secondary: '#ffd700', text: '#ffd700' },
    prestige: 18,
    stadium: 'Boca do Lobo',
    rival: 'Brasil de Pelotas',
  },
  {
    id: 'ferroviaria',
    name: 'Ferroviária',
    league: 'REGIONAL',
    city: 'Araraquara (SP)',
    country: '🇧🇷',
    badge: '🚂',
    colors: { primary: '#6b1d2f', secondary: '#ffffff', text: '#ffffff' },
    prestige: 22,
    stadium: 'Arena da Fonte',
    rival: 'Botafogo-SP',
  },
  {
    id: 'volta-redonda',
    name: 'Volta Redonda',
    league: 'REGIONAL',
    city: 'Volta Redonda (RJ)',
    country: '🇧🇷',
    badge: '⚡',
    colors: { primary: '#1a1a1a', secondary: '#ffd700', text: '#ffd700' },
    prestige: 20,
    stadium: 'Raulino de Oliveira',
    rival: 'Madureira',
  },
  {
    id: 'maringa',
    name: 'Maringá FC',
    league: 'REGIONAL',
    city: 'Maringá (PR)',
    country: '🇧🇷',
    badge: '🐕',
    colors: { primary: '#005a36', secondary: '#ffffff', text: '#ffffff' },
    prestige: 22,
    stadium: 'Willie Davids',
    rival: 'Londrina',
  },
  {
    id: 'campinense',
    name: 'Campinense',
    league: 'REGIONAL',
    city: 'Campina Grande (PB)',
    country: '🇧🇷',
    badge: '🦊',
    colors: { primary: '#c4122f', secondary: '#1a1a1a', text: '#ffffff' },
    prestige: 21,
    stadium: 'Amigão',
    rival: 'Treze',
  },

  // --- Série B (Brasileirão Série B) ---
  {
    id: 'coritiba',
    name: 'Coritiba',
    league: 'SERIE_B',
    city: 'Curitiba (PR)',
    country: '🇧🇷',
    badge: '🟢',
    colors: { primary: '#00543d', secondary: '#ffffff', text: '#ffffff' },
    prestige: 50,
    stadium: 'Couto Pereira',
    rival: 'Athletico-PR',
  },
  {
    id: 'sport',
    name: 'Sport Recife',
    league: 'SERIE_B',
    city: 'Recife (PE)',
    country: '🇧🇷',
    badge: '🦁',
    colors: { primary: '#c4122f', secondary: '#1a1a1a', text: '#ffd700' },
    prestige: 54,
    stadium: 'Ilha do Retiro',
    rival: 'Náutico',
  },
  {
    id: 'ceara',
    name: 'Ceará SC',
    league: 'SERIE_B',
    city: 'Fortaleza (CE)',
    country: '🇧🇷',
    badge: '👴',
    colors: { primary: '#1a1a1a', secondary: '#ffffff', text: '#ffffff' },
    prestige: 52,
    stadium: 'Castelão',
    rival: 'Fortaleza',
  },
  {
    id: 'goias',
    name: 'Goiás',
    league: 'SERIE_B',
    city: 'Goiânia (GO)',
    country: '🇧🇷',
    badge: '🦜',
    colors: { primary: '#00543d', secondary: '#ffffff', text: '#ffffff' },
    prestige: 49,
    stadium: 'Serrinha',
    rival: 'Vila Nova',
  },

  // --- Série A (Elite do Futebol Nacional) ---
  {
    id: 'gremio',
    name: 'Grêmio',
    league: 'SERIE_A',
    city: 'Porto Alegre (RS)',
    country: '🇧🇷',
    badge: '🔵',
    colors: { primary: '#0080ff', secondary: '#111111', text: '#ffffff' },
    prestige: 85,
    stadium: 'Arena do Grêmio',
    rival: 'Internacional',
  },
  {
    id: 'flamengo',
    name: 'Flamengo',
    league: 'SERIE_A',
    city: 'Rio de Janeiro (RJ)',
    country: '🇧🇷',
    badge: '🔴',
    colors: { primary: '#c4122f', secondary: '#111111', text: '#ffffff' },
    prestige: 90,
    stadium: 'Maracanã',
    rival: 'Vasco da Gama',
  },
  {
    id: 'palmeiras',
    name: 'Palmeiras',
    league: 'SERIE_A',
    city: 'São Paulo (SP)',
    country: '🇧🇷',
    badge: '🐷',
    colors: { primary: '#006437', secondary: '#ffffff', text: '#ffffff' },
    prestige: 88,
    stadium: 'Allianz Parque',
    rival: 'Corinthians',
  },
  {
    id: 'sao-paulo',
    name: 'São Paulo FC',
    league: 'SERIE_A',
    city: 'São Paulo (SP)',
    country: '🇧🇷',
    badge: '⚪',
    colors: { primary: '#c4122f', secondary: '#ffffff', text: '#111111' },
    prestige: 86,
    stadium: 'MorumBIS',
    rival: 'Palmeiras',
  },
  {
    id: 'internacional',
    name: 'Internacional',
    league: 'SERIE_A',
    city: 'Porto Alegre (RS)',
    country: '🇧🇷',
    badge: '🇦🇹',
    colors: { primary: '#d4001a', secondary: '#ffffff', text: '#ffffff' },
    prestige: 84,
    stadium: 'Beira-Rio',
    rival: 'Grêmio',
  },
  {
    id: 'atletico-mg',
    name: 'Atlético Mineiro',
    league: 'SERIE_A',
    city: 'Belo Horizonte (MG)',
    country: '🇧🇷',
    badge: '🐔',
    colors: { primary: '#111111', secondary: '#ffffff', text: '#ffffff' },
    prestige: 83,
    stadium: 'Arena MRV',
    rival: 'Cruzeiro',
  },

  // --- Ligas Milionárias (Petrodólares / China / Arábia) ---
  {
    id: 'al-hilal',
    name: 'Al-Hilal',
    league: 'MONEY_LEAGUE',
    city: 'Riad',
    country: '🇸🇦',
    badge: '🌙',
    colors: { primary: '#002b80', secondary: '#ffffff', text: '#ffffff' },
    prestige: 68,
    stadium: 'Kingdom Arena',
    rival: 'Al-Nassr',
  },
  {
    id: 'al-nassr',
    name: 'Al-Nassr',
    league: 'MONEY_LEAGUE',
    city: 'Riad',
    country: '🇸🇦',
    badge: '👑',
    colors: { primary: '#ffd700', secondary: '#002b80', text: '#002b80' },
    prestige: 69,
    stadium: 'Al-Awwal Park',
    rival: 'Al-Hilal',
  },
  {
    id: 'shanghai-port',
    name: 'Shanghai Port',
    league: 'MONEY_LEAGUE',
    city: 'Xangai',
    country: '🇨🇳',
    badge: '🐉',
    colors: { primary: '#d4001a', secondary: '#ffd700', text: '#ffffff' },
    prestige: 58,
    stadium: 'Pudong Football Stadium',
    rival: 'Shanghai Shenhua',
  },

  // --- Europa Média / Vitrine ---
  {
    id: 'benfica',
    name: 'SL Benfica',
    league: 'EUROPA_MEDIA',
    city: 'Lisboa',
    country: '🇵🇹',
    badge: '🦅',
    colors: { primary: '#d4001a', secondary: '#ffffff', text: '#ffffff' },
    prestige: 82,
    stadium: 'Estádio da Luz',
    rival: 'Sporting CP',
  },
  {
    id: 'porto',
    name: 'FC Porto',
    league: 'EUROPA_MEDIA',
    city: 'Porto',
    country: '🇵🇹',
    badge: '🐉',
    colors: { primary: '#003882', secondary: '#ffffff', text: '#ffffff' },
    prestige: 81,
    stadium: 'Estádio do Dragão',
    rival: 'Benfica',
  },
  {
    id: 'sevilla',
    name: 'Sevilla FC',
    league: 'EUROPA_MEDIA',
    city: 'Sevilha',
    country: '🇪🇸',
    badge: '⚔️',
    colors: { primary: '#d4001a', secondary: '#ffffff', text: '#ffffff' },
    prestige: 80,
    stadium: 'Ramón Sánchez Pizjuán',
    rival: 'Real Betis',
  },
  {
    id: 'ajax',
    name: 'AFC Ajax',
    league: 'EUROPA_MEDIA',
    city: 'Amsterdã',
    country: '🇳🇱',
    badge: '🛡️',
    colors: { primary: '#d4001a', secondary: '#ffffff', text: '#ffffff' },
    prestige: 81,
    stadium: 'Johan Cruyff Arena',
    rival: 'Feyenoord',
  },

  // --- Gigantes da Europa (Topo do Mundo) ---
  {
    id: 'real-madrid',
    name: 'Real Madrid',
    league: 'GIGANTES_EUROPA',
    city: 'Madri',
    country: '🇪🇸',
    badge: '👑',
    colors: { primary: '#ffffff', secondary: '#4d1e8c', text: '#111111' },
    prestige: 99,
    stadium: 'Santiago Bernabéu',
    rival: 'Barcelona',
  },
  {
    id: 'barcelona',
    name: 'FC Barcelona',
    league: 'GIGANTES_EUROPA',
    city: 'Barcelona',
    country: '🇪🇸',
    badge: '🔴🔵',
    colors: { primary: '#004d98', secondary: '#a50044', text: '#ffd700' },
    prestige: 97,
    stadium: 'Spotify Camp Nou',
    rival: 'Real Madrid',
  },
  {
    id: 'manchester-city',
    name: 'Manchester City',
    league: 'GIGANTES_EUROPA',
    city: 'Manchester',
    country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    badge: '⛵',
    colors: { primary: '#6cabdd', secondary: '#1c2c5b', text: '#ffffff' },
    prestige: 98,
    stadium: 'Etihad Stadium',
    rival: 'Manchester United',
  },
  {
    id: 'bayern',
    name: 'Bayern München',
    league: 'GIGANTES_EUROPA',
    city: 'Munique',
    country: '🇩🇪',
    badge: '🦁',
    colors: { primary: '#dc052d', secondary: '#0066b2', text: '#ffffff' },
    prestige: 97,
    stadium: 'Allianz Arena',
    rival: 'Borussia Dortmund',
  },
];

export function getStartingClubs() {
  return CLUBS.filter((c) => c.league === 'REGIONAL');
}

export function getClubById(clubId) {
  return CLUBS.find((c) => c.id === clubId) || CLUBS[0];
}

export function getLeagueById(leagueId) {
  return LEAGUES[leagueId] || LEAGUES.REGIONAL;
}
