/* ==========================================================================
   CLUBS & LEAGUES DATABASE • SOCCERWIKI POWERED
   Comprehensive football ecosystem from grassroots to global giants
   ========================================================================== */

export const LEAGUES = {
  REGIONAL: {
    id: 'regional',
    name: 'Série D / Acesso Regional',
    category: 'domestic_regional',
    country: '🇧🇷',
    repTier: 1,
    avgSalaryRange: [2500, 8000],
    signingBonusRange: [0, 20000],
  },
  SERIE_B: {
    id: 'serie_b',
    name: 'Brasileirão Série B',
    category: 'domestic_b',
    country: '🇧🇷',
    repTier: 2,
    avgSalaryRange: [15000, 50000],
    signingBonusRange: [50000, 250000],
  },
  SERIE_A: {
    id: 'serie_a',
    name: 'Brasileirão Série A (Elite)',
    category: 'domestic_a',
    country: '🇧🇷',
    repTier: 3,
    avgSalaryRange: [80000, 450000],
    signingBonusRange: [500000, 3000000],
  },
  LIBERTADORES: {
    id: 'libertadores',
    name: 'América do Sul / Libertadores',
    category: 'south_america',
    country: '🌎',
    repTier: 3,
    avgSalaryRange: [70000, 350000],
    signingBonusRange: [400000, 2000000],
  },
  PORTUGAL: {
    id: 'portugal',
    name: 'Liga Portugal (Vitrine Europeia)',
    category: 'europe_mid',
    country: '🇵🇹',
    repTier: 4,
    avgSalaryRange: [120000, 550000],
    signingBonusRange: [1000000, 5000000],
  },
  PREMIER_LEAGUE: {
    id: 'premier_league',
    name: 'Premier League (Inglaterra)',
    category: 'europe_top',
    country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    repTier: 5,
    avgSalaryRange: [1500000, 5500000],
    signingBonusRange: [15000000, 60000000],
  },
  LA_LIGA: {
    id: 'la_liga',
    name: 'La Liga (Espanha)',
    category: 'europe_top',
    country: '🇪🇸',
    repTier: 5,
    avgSalaryRange: [1200000, 5000000],
    signingBonusRange: [12000000, 50000000],
  },
  SERIE_A_ITALIA: {
    id: 'serie_a_italia',
    name: 'Serie A (Itália)',
    category: 'europe_top',
    country: '🇮🇹',
    repTier: 5,
    avgSalaryRange: [1000000, 4000000],
    signingBonusRange: [10000000, 40000000],
  },
  BUNDESLIGA: {
    id: 'bundesliga',
    name: 'Bundesliga (Alemanha)',
    category: 'europe_top',
    country: '🇩🇪',
    repTier: 5,
    avgSalaryRange: [1100000, 4500000],
    signingBonusRange: [12000000, 45000000],
  },
  LIGUE_1: {
    id: 'ligue_1',
    name: 'Ligue 1 (França)',
    category: 'europe_top',
    country: '🇫🇷',
    repTier: 5,
    avgSalaryRange: [1000000, 4500000],
    signingBonusRange: [10000000, 45000000],
  },
  MONEY_LEAGUE: {
    id: 'money_league',
    name: 'Saudi Pro League & MLS (Petrodólares)',
    category: 'petrodollar',
    country: '🇸🇦',
    repTier: 3, // Low international prestige, massive financial power
    avgSalaryRange: [700000, 3000000],
    signingBonusRange: [8000000, 30000000],
  },
};

export const CLUBS = [
  // =========================================================================
  // 1. SÉRIE D / VÁRZEA / CLUBES FORMADORES (Ponto de Partida)
  // =========================================================================
  {
    id: 'sao-jose-rs',
    name: 'São José-RS',
    shortName: 'SJO',
    league: 'REGIONAL',
    city: 'Porto Alegre (RS)',
    country: '🇧🇷',
    badge: '🦅',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/3436.png',
    colors: { primary: '#0a3871', secondary: '#ffffff', text: '#ffffff' },
    prestige: 15,
    stadium: "Passo D'Areia",
    rival: 'Caxias',
  },
  {
    id: 'brasil-de-pelotas',
    name: 'Brasil de Pelotas',
    shortName: 'GEB',
    league: 'REGIONAL',
    city: 'Pelotas (RS)',
    country: '🇧🇷',
    badge: '🔴⚫',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/2478.png',
    colors: { primary: '#d90429', secondary: '#111111', text: '#ffffff' },
    prestige: 24,
    stadium: 'Bento Freitas',
    rival: 'Pelotas',
  },
  {
    id: 'ferroviaria',
    name: 'Ferroviária',
    shortName: 'FER',
    league: 'REGIONAL',
    city: 'Araraquara (SP)',
    country: '🇧🇷',
    badge: '🚂',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/3426.png',
    colors: { primary: '#6b1d2f', secondary: '#ffffff', text: '#ffffff' },
    prestige: 22,
    stadium: 'Arena da Fonte',
    rival: 'Botafogo-SP',
  },
  {
    id: 'volta-redonda',
    name: 'Volta Redonda',
    shortName: 'VRE',
    league: 'REGIONAL',
    city: 'Volta Redonda (RJ)',
    country: '🇧🇷',
    badge: '⚡',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/2475.png',
    colors: { primary: '#1a1a1a', secondary: '#ffd700', text: '#ffd700' },
    prestige: 20,
    stadium: 'Raulino de Oliveira',
    rival: 'Madureira',
  },
  {
    id: 'maringa',
    name: 'Maringá FC',
    shortName: 'MAR',
    league: 'REGIONAL',
    city: 'Maringá (PR)',
    country: '🇧🇷',
    badge: '🐕',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/3523.png',
    colors: { primary: '#005a36', secondary: '#ffffff', text: '#ffffff' },
    prestige: 22,
    stadium: 'Willie Davids',
    rival: 'Londrina',
  },
  {
    id: 'campinense',
    name: 'Campinense',
    shortName: 'CAM',
    league: 'REGIONAL',
    city: 'Campina Grande (PB)',
    country: '🇧🇷',
    badge: '🦊',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/2396.png',
    colors: { primary: '#c4122f', secondary: '#1a1a1a', text: '#ffffff' },
    prestige: 21,
    stadium: 'Amigão',
    rival: 'Treze',
  },
  {
    id: 'bangu',
    name: 'Bangu AC',
    shortName: 'BAN',
    league: 'REGIONAL',
    city: 'Rio de Janeiro (RJ)',
    country: '🇧🇷',
    badge: '🔴⚪',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/2815.png',
    colors: { primary: '#d90429', secondary: '#ffffff', text: '#ffffff' },
    prestige: 19,
    stadium: 'Moça Bonita',
    rival: 'Madureira',
  },
  {
    id: 'santa-cruz',
    name: 'Santa Cruz',
    shortName: 'SCZ',
    league: 'REGIONAL',
    city: 'Recife (PE)',
    country: '🇧🇷',
    badge: '🐍',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/603.png',
    colors: { primary: '#111111', secondary: '#d90429', text: '#ffffff' },
    prestige: 32,
    stadium: 'Arruda',
    rival: 'Sport Recife',
  },
  {
    id: 'portuguesa',
    name: 'Portuguesa',
    shortName: 'POR',
    league: 'REGIONAL',
    city: 'São Paulo (SP)',
    country: '🇧🇷',
    badge: '🦁',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/1232.png',
    colors: { primary: '#d90429', secondary: '#00543d', text: '#ffffff' },
    prestige: 30,
    stadium: 'Canindé',
    rival: 'Juventus-SP',
  },

  // =========================================================================
  // 2. BRASILEIRÃO SÉRIE B (Acesso e Visibilidade Nacional)
  // =========================================================================
  {
    id: 'sport',
    name: 'Sport Recife',
    shortName: 'SPT',
    league: 'SERIE_B',
    city: 'Recife (PE)',
    country: '🇧🇷',
    badge: '🦁',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/923.png',
    colors: { primary: '#c4122f', secondary: '#1a1a1a', text: '#ffd700' },
    prestige: 56,
    stadium: 'Ilha do Retiro',
    rival: 'Náutico',
  },
  {
    id: 'ceara',
    name: 'Ceará SC',
    shortName: 'CEA',
    league: 'SERIE_B',
    city: 'Fortaleza (CE)',
    country: '🇧🇷',
    badge: '👴',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/1458.png',
    colors: { primary: '#1a1a1a', secondary: '#ffffff', text: '#ffffff' },
    prestige: 54,
    stadium: 'Arena Castelão',
    rival: 'Fortaleza',
  },
  {
    id: 'coritiba',
    name: 'Coritiba',
    shortName: 'CFC',
    league: 'SERIE_B',
    city: 'Curitiba (PR)',
    country: '🇧🇷',
    badge: '🟢',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/291.png',
    colors: { primary: '#00543d', secondary: '#ffffff', text: '#ffffff' },
    prestige: 52,
    stadium: 'Couto Pereira',
    rival: 'Athletico-PR',
  },
  {
    id: 'goias',
    name: 'Goiás',
    shortName: 'GOI',
    league: 'SERIE_B',
    city: 'Goiânia (GO)',
    country: '🇧🇷',
    badge: '🦜',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/297.png',
    colors: { primary: '#00543d', secondary: '#ffffff', text: '#ffffff' },
    prestige: 51,
    stadium: 'Serrinha',
    rival: 'Vila Nova',
  },
  {
    id: 'ponte-preta',
    name: 'Ponte Preta',
    shortName: 'PON',
    league: 'SERIE_B',
    city: 'Campinas (SP)',
    country: '🇧🇷',
    badge: '🐵',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/303.png',
    colors: { primary: '#111111', secondary: '#ffffff', text: '#ffffff' },
    prestige: 48,
    stadium: 'Moisés Lucarelli',
    rival: 'Guarani',
  },
  {
    id: 'guarani',
    name: 'Guarani FC',
    shortName: 'GUA',
    league: 'SERIE_B',
    city: 'Campinas (SP)',
    country: '🇧🇷',
    badge: '🏹',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/1515.png',
    colors: { primary: '#00543d', secondary: '#ffffff', text: '#ffffff' },
    prestige: 47,
    stadium: 'Brinco de Ouro',
    rival: 'Ponte Preta',
  },
  {
    id: 'avai',
    name: 'Avaí FC',
    shortName: 'AVA',
    league: 'SERIE_B',
    city: 'Florianópolis (SC)',
    country: '🇧🇷',
    badge: '🦁',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/1414.png',
    colors: { primary: '#0047ab', secondary: '#ffffff', text: '#ffffff' },
    prestige: 49,
    stadium: 'Ressacada',
    rival: 'Figueirense',
  },
  {
    id: 'chapecoense',
    name: 'Chapecoense',
    shortName: 'CHA',
    league: 'SERIE_B',
    city: 'Chapecó (SC)',
    country: '🇧🇷',
    badge: '🏹',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/2379.png',
    colors: { primary: '#00543d', secondary: '#ffffff', text: '#ffffff' },
    prestige: 50,
    stadium: 'Arena Condá',
    rival: 'Criciúma',
  },
  {
    id: 'novorizontino',
    name: 'Novorizontino',
    shortName: 'NOV',
    league: 'SERIE_B',
    city: 'Novo Horizonte (SP)',
    country: '🇧🇷',
    badge: '🐯',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/3481.png',
    colors: { primary: '#ffd700', secondary: '#111111', text: '#111111' },
    prestige: 46,
    stadium: 'Jorjão',
    rival: 'Mirassol',
  },

  // =========================================================================
  // 3. BRASILEIRÃO SÉRIE A (Elite do Futebol Nacional)
  // =========================================================================
  {
    id: 'flamengo',
    name: 'Flamengo',
    shortName: 'FLA',
    league: 'SERIE_A',
    city: 'Rio de Janeiro (RJ)',
    country: '🇧🇷',
    badge: '🔴',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/294.png',
    colors: { primary: '#c4122f', secondary: '#111111', text: '#ffffff' },
    prestige: 91,
    stadium: 'Maracanã',
    rival: 'Vasco da Gama',
  },
  {
    id: 'palmeiras',
    name: 'Palmeiras',
    shortName: 'PAL',
    league: 'SERIE_A',
    city: 'São Paulo (SP)',
    country: '🇧🇷',
    badge: '🐷',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/300.png',
    colors: { primary: '#006437', secondary: '#ffffff', text: '#ffffff' },
    prestige: 89,
    stadium: 'Allianz Parque',
    rival: 'Corinthians',
  },
  {
    id: 'sao-paulo',
    name: 'São Paulo FC',
    shortName: 'SAO',
    league: 'SERIE_A',
    city: 'São Paulo (SP)',
    country: '🇧🇷',
    badge: '⚪',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/306.png',
    colors: { primary: '#c4122f', secondary: '#ffffff', text: '#111111' },
    prestige: 87,
    stadium: 'MorumBIS',
    rival: 'Palmeiras',
  },
  {
    id: 'corinthians',
    name: 'Corinthians',
    shortName: 'COR',
    league: 'SERIE_A',
    city: 'São Paulo (SP)',
    country: '🇧🇷',
    badge: '🦅',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/290.png',
    colors: { primary: '#111111', secondary: '#ffffff', text: '#ffffff' },
    prestige: 86,
    stadium: 'Neo Química Arena',
    rival: 'Palmeiras',
  },
  {
    id: 'gremio',
    name: 'Grêmio',
    shortName: 'GRE',
    league: 'SERIE_A',
    city: 'Porto Alegre (RS)',
    country: '🇧🇷',
    badge: '🔵',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/602.png',
    colors: { primary: '#0080ff', secondary: '#111111', text: '#ffffff' },
    prestige: 85,
    stadium: 'Arena do Grêmio',
    rival: 'Internacional',
  },
  {
    id: 'internacional',
    name: 'Internacional',
    shortName: 'INT',
    league: 'SERIE_A',
    city: 'Porto Alegre (RS)',
    country: '🇧🇷',
    badge: '🇦🇹',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/298.png',
    colors: { primary: '#d4001a', secondary: '#ffffff', text: '#ffffff' },
    prestige: 84,
    stadium: 'Beira-Rio',
    rival: 'Grêmio',
  },
  {
    id: 'atletico-mg',
    name: 'Atlético Mineiro',
    shortName: 'CAM',
    league: 'SERIE_A',
    city: 'Belo Horizonte (MG)',
    country: '🇧🇷',
    badge: '🐔',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/286.png',
    colors: { primary: '#111111', secondary: '#ffffff', text: '#ffffff' },
    prestige: 84,
    stadium: 'Arena MRV',
    rival: 'Cruzeiro',
  },
  {
    id: 'cruzeiro',
    name: 'Cruzeiro EC',
    shortName: 'CRU',
    league: 'SERIE_A',
    city: 'Belo Horizonte (MG)',
    country: '🇧🇷',
    badge: '🦊',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/292.png',
    colors: { primary: '#003882', secondary: '#ffffff', text: '#ffffff' },
    prestige: 83,
    stadium: 'Mineirão',
    rival: 'Atlético Mineiro',
  },
  {
    id: 'botafogo',
    name: 'Botafogo FR',
    shortName: 'BOT',
    league: 'SERIE_A',
    city: 'Rio de Janeiro (RJ)',
    country: '🇧🇷',
    badge: '⭐',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/288.png',
    colors: { primary: '#111111', secondary: '#ffffff', text: '#ffffff' },
    prestige: 85,
    stadium: 'Nilton Santos',
    rival: 'Flamengo',
  },
  {
    id: 'fluminense',
    name: 'Fluminense',
    shortName: 'FLU',
    league: 'SERIE_A',
    city: 'Rio de Janeiro (RJ)',
    country: '🇧🇷',
    badge: '🇭🇺',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/295.png',
    colors: { primary: '#8b1d2f', secondary: '#005a36', text: '#ffffff' },
    prestige: 84,
    stadium: 'Maracanã',
    rival: 'Flamengo',
  },
  {
    id: 'vasco',
    name: 'Vasco da Gama',
    shortName: 'VAS',
    league: 'SERIE_A',
    city: 'Rio de Janeiro (RJ)',
    country: '🇧🇷',
    badge: '⛵',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/307.png',
    colors: { primary: '#111111', secondary: '#ffffff', text: '#ffffff' },
    prestige: 82,
    stadium: 'São Januário',
    rival: 'Flamengo',
  },
  {
    id: 'santos',
    name: 'Santos FC',
    shortName: 'SAN',
    league: 'SERIE_A',
    city: 'Santos (SP)',
    country: '🇧🇷',
    badge: '🐋',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/304.png',
    colors: { primary: '#ffffff', secondary: '#111111', text: '#111111' },
    prestige: 83,
    stadium: 'Vila Belmiro',
    rival: 'São Paulo',
  },
  {
    id: 'bahia',
    name: 'EC Bahia',
    shortName: 'BAH',
    league: 'SERIE_A',
    city: 'Salvador (BA)',
    country: '🇧🇷',
    badge: '🔵🔴',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/1473.png',
    colors: { primary: '#0047ab', secondary: '#d4001a', text: '#ffffff' },
    prestige: 80,
    stadium: 'Arena Fonte Nova',
    rival: 'Vitória',
  },
  {
    id: 'fortaleza',
    name: 'Fortaleza EC',
    shortName: 'FOR',
    league: 'SERIE_A',
    city: 'Fortaleza (CE)',
    country: '🇧🇷',
    badge: '🦁',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/296.png',
    colors: { primary: '#003882', secondary: '#d4001a', text: '#ffffff' },
    prestige: 81,
    stadium: 'Arena Castelão',
    rival: 'Ceará',
  },
  {
    id: 'athletico-pr',
    name: 'Athletico Paranaense',
    shortName: 'CAP',
    league: 'SERIE_A',
    city: 'Curitiba (PR)',
    country: '🇧🇷',
    badge: '🌪️',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/287.png',
    colors: { primary: '#c4122f', secondary: '#111111', text: '#ffffff' },
    prestige: 82,
    stadium: 'Ligga Arena',
    rival: 'Coritiba',
  },
  {
    id: 'bragantino',
    name: 'RB Bragantino',
    shortName: 'RBB',
    league: 'SERIE_A',
    city: 'Bragança Paulista (SP)',
    country: '🇧🇷',
    badge: '🐂',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/1447.png',
    colors: { primary: '#ffffff', secondary: '#c4122f', text: '#111111' },
    prestige: 79,
    stadium: 'Nabi Abi Chedid',
    rival: 'Ponte Preta',
  },

  // =========================================================================
  // 4. CONMEBOL LIBERTADORES (Gigantes da América do Sul)
  // =========================================================================
  {
    id: 'boca-juniors',
    name: 'Boca Juniors',
    shortName: 'BOC',
    league: 'LIBERTADORES',
    city: 'Buenos Aires',
    country: '🇦🇷',
    badge: '🔷🔶',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/270.png',
    colors: { primary: '#002f6c', secondary: '#ffd700', text: '#ffd700' },
    prestige: 88,
    stadium: 'La Bombonera',
    rival: 'River Plate',
  },
  {
    id: 'river-plate',
    name: 'River Plate',
    shortName: 'RIV',
    league: 'LIBERTADORES',
    city: 'Buenos Aires',
    country: '🇦🇷',
    badge: '⚪🔴',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/282.png',
    colors: { primary: '#ffffff', secondary: '#d90429', text: '#111111' },
    prestige: 89,
    stadium: 'Mâs Monumental',
    rival: 'Boca Juniors',
  },
  {
    id: 'penarol',
    name: 'Peñarol',
    shortName: 'PEN',
    league: 'LIBERTADORES',
    city: 'Montevidéu',
    country: '🇺🇾',
    badge: '🟡⚫',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/376.png',
    colors: { primary: '#ffd700', secondary: '#111111', text: '#111111' },
    prestige: 82,
    stadium: 'Campeón del Siglo',
    rival: 'Nacional',
  },
  {
    id: 'nacional-uru',
    name: 'Nacional',
    shortName: 'NAC',
    league: 'LIBERTADORES',
    city: 'Montevidéu',
    country: '🇺🇾',
    badge: '🔵⚪🔴',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/375.png',
    colors: { primary: '#003882', secondary: '#ffffff', text: '#ffffff' },
    prestige: 81,
    stadium: 'Gran Parque Central',
    rival: 'Peñarol',
  },
  {
    id: 'olimpia',
    name: 'Club Olimpia',
    shortName: 'OLI',
    league: 'LIBERTADORES',
    city: 'Assunção',
    country: '🇵🇾',
    badge: '⚪⚫',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/613.png',
    colors: { primary: '#ffffff', secondary: '#111111', text: '#111111' },
    prestige: 80,
    stadium: 'Manuel Ferreira',
    rival: 'Cerro Porteño',
  },
  {
    id: 'colo-colo',
    name: 'Colo-Colo',
    shortName: 'COL',
    league: 'LIBERTADORES',
    city: 'Santiago',
    country: '🇨🇱',
    badge: '⚪⚫',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/362.png',
    colors: { primary: '#ffffff', secondary: '#111111', text: '#111111' },
    prestige: 79,
    stadium: 'Monumental David Arellano',
    rival: 'U. de Chile',
  },
  {
    id: 'independiente-del-valle',
    name: 'Independiente del Valle',
    shortName: 'IDV',
    league: 'LIBERTADORES',
    city: 'Quito',
    country: '🇪🇨',
    badge: '⚫🔵',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/1562.png',
    colors: { primary: '#111111', secondary: '#00543d', text: '#ffffff' },
    prestige: 78,
    stadium: 'Banco Guayaquil',
    rival: 'LDU Quito',
  },
  {
    id: 'ldu-quito',
    name: 'LDU Quito',
    shortName: 'LDU',
    league: 'LIBERTADORES',
    city: 'Quito',
    country: '🇪🇨',
    badge: '⚪',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/656.png',
    colors: { primary: '#ffffff', secondary: '#d90429', text: '#111111' },
    prestige: 78,
    stadium: 'Rodrigo Paz Delgado',
    rival: 'Barcelona SC',
  },

  // =========================================================================
  // 5. LIGA PORTUGAL (Porta de Entrada & Vitrine Europeia)
  // =========================================================================
  {
    id: 'benfica',
    name: 'SL Benfica',
    shortName: 'SLB',
    league: 'PORTUGAL',
    city: 'Lisboa',
    country: '🇵🇹',
    badge: '🦅',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/218.png',
    colors: { primary: '#d4001a', secondary: '#ffffff', text: '#ffffff' },
    prestige: 86,
    stadium: 'Estádio da Luz',
    rival: 'Sporting CP',
  },
  {
    id: 'porto',
    name: 'FC Porto',
    shortName: 'FCP',
    league: 'PORTUGAL',
    city: 'Porto',
    country: '🇵🇹',
    badge: '🐉',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/224.png',
    colors: { primary: '#003882', secondary: '#ffffff', text: '#ffffff' },
    prestige: 85,
    stadium: 'Estádio do Dragão',
    rival: 'Benfica',
  },
  {
    id: 'sporting',
    name: 'Sporting CP',
    shortName: 'SCP',
    league: 'PORTUGAL',
    city: 'Lisboa',
    country: '🇵🇹',
    badge: '🦁',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/246.png',
    colors: { primary: '#006437', secondary: '#ffffff', text: '#ffffff' },
    prestige: 85,
    stadium: 'José Alvalade',
    rival: 'Benfica',
  },

  // =========================================================================
  // 6. PREMIER LEAGUE (A Liga Mais Disputada do Planeta)
  // =========================================================================
  {
    id: 'manchester-city',
    name: 'Manchester City',
    shortName: 'MCI',
    league: 'PREMIER_LEAGUE',
    city: 'Manchester',
    country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    badge: '⛵',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/47.png',
    colors: { primary: '#6cabdd', secondary: '#1c2c5b', text: '#ffffff' },
    prestige: 98,
    stadium: 'Etihad Stadium',
    rival: 'Manchester United',
  },
  {
    id: 'arsenal',
    name: 'Arsenal',
    shortName: 'ARS',
    league: 'PREMIER_LEAGUE',
    city: 'Londres',
    country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    badge: '🔴⚪',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/1.png',
    colors: { primary: '#db0007', secondary: '#ffffff', text: '#ffffff' },
    prestige: 95,
    stadium: 'Emirates Stadium',
    rival: 'Tottenham',
  },
  {
    id: 'liverpool',
    name: 'Liverpool',
    shortName: 'LIV',
    league: 'PREMIER_LEAGUE',
    city: 'Liverpool',
    country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    badge: '🦅',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/44.png',
    colors: { primary: '#c8102e', secondary: '#00b2a9', text: '#ffffff' },
    prestige: 96,
    stadium: 'Anfield',
    rival: 'Everton',
  },

  // =========================================================================
  // 7. LA LIGA (Espanha)
  // =========================================================================
  {
    id: 'real-madrid',
    name: 'Real Madrid',
    shortName: 'RMA',
    league: 'LA_LIGA',
    city: 'Madri',
    country: '🇪🇸',
    badge: '👑',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/163.png',
    colors: { primary: '#ffffff', secondary: '#4d1e8c', text: '#111111' },
    prestige: 99,
    stadium: 'Santiago Bernabéu',
    rival: 'Barcelona',
  },
  {
    id: 'barcelona',
    name: 'FC Barcelona',
    shortName: 'FCB',
    league: 'LA_LIGA',
    city: 'Barcelona',
    country: '🇪🇸',
    badge: '🔴🔵',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/140.png',
    colors: { primary: '#004d98', secondary: '#a50044', text: '#ffd700' },
    prestige: 97,
    stadium: 'Spotify Camp Nou',
    rival: 'Real Madrid',
  },

  // =========================================================================
  // 8. SERIE A (Itália)
  // =========================================================================
  {
    id: 'inter-milao',
    name: 'Internazionale',
    shortName: 'INT',
    league: 'SERIE_A_ITALIA',
    city: 'Milão',
    country: '🇮🇹',
    badge: '🐍',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/109.png',
    colors: { primary: '#001489', secondary: '#000000', text: '#ffffff' },
    prestige: 94,
    stadium: 'San Siro',
    rival: 'Milan',
  },
  {
    id: 'juventus',
    name: 'Juventus',
    shortName: 'JUV',
    league: 'SERIE_A_ITALIA',
    city: 'Turim',
    country: '🇮🇹',
    badge: '⚪⚫',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/110.png',
    colors: { primary: '#000000', secondary: '#ffffff', text: '#ffffff' },
    prestige: 93,
    stadium: 'Allianz Stadium',
    rival: 'Torino',
  },

  // =========================================================================
  // 9. BUNDESLIGA & LIGUE 1
  // =========================================================================
  {
    id: 'bayern',
    name: 'Bayern München',
    shortName: 'BAY',
    league: 'BUNDESLIGA',
    city: 'Munique',
    country: '🇩🇪',
    badge: '🦁',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/391.png',
    colors: { primary: '#dc052d', secondary: '#0066b2', text: '#ffffff' },
    prestige: 97,
    stadium: 'Allianz Arena',
    rival: 'Borussia Dortmund',
  },
  {
    id: 'psg',
    name: 'Paris Saint-Germain',
    shortName: 'PSG',
    league: 'LIGUE_1',
    city: 'Paris',
    country: '🇫🇷',
    badge: '🗼',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/338.png',
    colors: { primary: '#004170', secondary: '#da291c', text: '#ffffff' },
    prestige: 96,
    stadium: 'Parc des Princes',
    rival: 'Marseille',
  },

  // =========================================================================
  // 10. PETRODÓLARES & LIGAS ALTERNATIVAS (Arábia & MLS)
  // =========================================================================
  {
    id: 'al-hilal',
    name: 'Al-Hilal SFC',
    shortName: 'HIL',
    league: 'MONEY_LEAGUE',
    city: 'Riad',
    country: '🇸🇦',
    badge: '🌙',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/625.png',
    colors: { primary: '#002b80', secondary: '#ffffff', text: '#ffffff' },
    prestige: 70,
    stadium: 'Kingdom Arena',
    rival: 'Al-Nassr',
  },
  {
    id: 'al-nassr',
    name: 'Al-Nassr FC',
    shortName: 'NAS',
    league: 'MONEY_LEAGUE',
    city: 'Riad',
    country: '🇸🇦',
    badge: '👑',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/665.png',
    colors: { primary: '#ffd700', secondary: '#002b80', text: '#002b80' },
    prestige: 70,
    stadium: 'Al-Awwal Park',
    rival: 'Al-Hilal',
  },
  {
    id: 'al-ittihad',
    name: 'Al-Ittihad Club',
    shortName: 'ITT',
    league: 'MONEY_LEAGUE',
    city: 'Jidá',
    country: '🇸🇦',
    badge: '🐅',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/627.png',
    colors: { primary: '#ffd700', secondary: '#111111', text: '#111111' },
    prestige: 69,
    stadium: 'King Abdullah Sports City',
    rival: 'Al-Ahli',
  },
  {
    id: 'al-ahli',
    name: 'Al-Ahli SFC',
    shortName: 'AHL',
    league: 'MONEY_LEAGUE',
    city: 'Jidá',
    country: '🇸🇦',
    badge: '🟢',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/628.png',
    colors: { primary: '#00543d', secondary: '#ffffff', text: '#ffffff' },
    prestige: 68,
    stadium: 'Prince Abdullah Al-Faisal',
    rival: 'Al-Ittihad',
  },
  {
    id: 'inter-miami',
    name: 'Inter Miami CF',
    shortName: 'MIA',
    league: 'MONEY_LEAGUE',
    city: 'Miami',
    country: '🇺🇸',
    badge: '🦩',
    logoUrl: 'https://cdn.soccerwiki.org/images/logos/clubs/5228.png',
    colors: { primary: '#f7b5cd', secondary: '#111111', text: '#111111' },
    prestige: 67,
    stadium: 'Chase Stadium',
    rival: 'Orlando City',
  },
];

export function getStartingClubs() {
  return CLUBS.filter((c) => c.league === 'REGIONAL');
}

export function getClubById(clubId) {
  return CLUBS.find((c) => c.id === clubId) || CLUBS[0];
}

export function getLeagueById(leagueId) {
  return LEAGUES[leagueId] || LEAGUES.REGIONAL;
}
